---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-netdata
      ansible.builtin.include_role:
        name: ansible-netdata
  vars:
    netdata_epel_setup: "{{ ansible_hostname == 'centos7' }}"
